### ISSUE TITLE
coloana order_id nu exista

### ISSUE THREAD

**Issue by georgesabin** [cipriancozma/books-app#3]
Salut! Sa te uiti peste eroarea asta, la migrare:
![image](https://user-images.githubusercontent.com/18421700/83229837-56fd6b80-a191-11ea-92de-1323bed49df3.png)

In tabela orders trebuie sa folosesti `$table->unsignedBigInteger('user_id');` inainte de a adauga acel foreign contraint.

![image](https://user-images.githubusercontent.com/18421700/83230071-cf642c80-a191-11ea-84d9-630f84ed7ab8.png)

**Comment by cipriancozma** [comment]
Mie imi merge. Nu am nicio eroare aici. Dar am sa investighez.

**Comment by cipriancozma** [comment]
Cred ca am rezolvat. Te rog sa te uiti.

**Comment by georgesabin** [comment]
Da, e ok!
